version: "3"
services:
  node:
    image: node:16-slim
    environment:
      # activate hot reload
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: >
      bash -c "yarn && yarn start"
    ports:
      - ${IP}:${PORT}:3000
    env_file:
      - .env
      # デフォでlocal適用
      - .env.local

volumes:
  node_modules:
